import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import '../data/cv_data.dart';
import '../theme/app_theme.dart';
import '../widgets/chatbot_widget.dart';
import 'about_section.dart';
import 'contact_section.dart';
import 'education_section.dart';
import 'experience_section.dart';
import 'projects_section.dart';
import 'skills_section.dart';

class HomePage extends StatefulWidget { const HomePage({super.key}); @override State<HomePage> createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{ final controller=ScrollController(); int selected=0; SiteLanguage language=SiteLanguage.en; final keys=List.generate(6, (_)=>GlobalKey()); final icons=[Icons.person_outline,Icons.work_outline,Icons.school_outlined,Icons.bolt_outlined,Icons.folder_copy_outlined,Icons.mail_outline];
void go(int i){ setState(()=>selected=i); Scrollable.ensureVisible(keys[i].currentContext!, duration:450.ms, curve:Curves.easeInOut);}
void toggleLanguage(bool spanish){ setState(()=>language=spanish?SiteLanguage.es:SiteLanguage.en); }
@override void dispose(){controller.dispose();super.dispose();}
@override Widget build(BuildContext context){ final desktop=MediaQuery.sizeOf(context).width>900; final content=cvContent(language); final text=uiText(language); final labels=text.navLabels; return Scaffold(bottomNavigationBar:desktop?null:NavigationBar(selectedIndex:selected,onDestinationSelected:go,destinations:List.generate(labels.length,(i)=>NavigationDestination(icon:Icon(icons[i]), label:labels[i]))), body:Stack(children:[Row(children:[if(desktop)_Sidebar(info:content.personalInfo,text:text,language:language,labels:labels,icons:icons,selected:selected,onTap:go,onLanguageChanged:toggleLanguage), Expanded(child:CustomScrollView(controller:controller, slivers:[SliverToBoxAdapter(child:Padding(padding:EdgeInsets.fromLTRB(desktop?56:20, desktop?48:28, desktop?56:20, 80), child:Column(crossAxisAlignment:CrossAxisAlignment.start, children:[if(!desktop) _MobileHeader(info:content.personalInfo,text:text,language:language,onLanguageChanged:toggleLanguage), _Section(key:keys[0], child:AboutSection(info:content.personalInfo,text:text)), _Section(key:keys[1], child:ExperienceSection(experiences:content.experiences,text:text)), _Section(key:keys[2], child:EducationSection(education:content.education,certifications:content.certifications,text:text)), _Section(key:keys[3], child:SkillsSection(categories:content.skillCategories,text:text)), _Section(key:keys[4], child:ProjectsSection(projects:content.projects,text:text)), _Section(key:keys[5], child:ContactSection(info:content.personalInfo,text:text))])))]))]), ChatbotWidget(text:text)]));}}
class _Section extends StatelessWidget{ const _Section({super.key, required this.child}); final Widget child; @override Widget build(BuildContext context)=>child;}
class _MobileHeader extends StatelessWidget{ const _MobileHeader({required this.info, required this.text, required this.language, required this.onLanguageChanged}); final PersonalInfo info; final UiText text; final SiteLanguage language; final ValueChanged<bool> onLanguageChanged; @override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(bottom:20), child:Column(crossAxisAlignment:CrossAxisAlignment.start, children:[Align(alignment:Alignment.centerRight, child:LanguageSwitch(language:language,onChanged:onLanguageChanged)), const SizedBox(height:12), Text(info.name, style:Theme.of(context).textTheme.displayMedium), const SizedBox(height:6), Text(info.title, style:const TextStyle(color:AppColors.teal,fontWeight:FontWeight.w700))]));}
class _Sidebar extends StatelessWidget{ const _Sidebar({required this.info, required this.text, required this.language, required this.labels,required this.icons,required this.selected,required this.onTap,required this.onLanguageChanged}); final PersonalInfo info; final UiText text; final SiteLanguage language; final List<String> labels; final List<IconData> icons; final int selected; final ValueChanged<int> onTap; final ValueChanged<bool> onLanguageChanged; @override Widget build(BuildContext context)=>Container(width:240, padding:const EdgeInsets.all(22), decoration:const BoxDecoration(color:AppColors.card,border:Border(right:BorderSide(color:AppColors.border))), child:Column(crossAxisAlignment:CrossAxisAlignment.start, children:[Align(alignment:Alignment.centerRight, child:LanguageSwitch(language:language,onChanged:onLanguageChanged)), const SizedBox(height:12), const Center(child:CircleAvatar(radius:44,backgroundColor:AppColors.teal,child:Text('LC',style:TextStyle(fontSize:26,color:AppColors.background,fontWeight:FontWeight.w900)))), const SizedBox(height:18), Text(info.name, style:Theme.of(context).textTheme.titleLarge, textAlign:TextAlign.center), const SizedBox(height:8), Text(info.title, style:const TextStyle(color:AppColors.muted), textAlign:TextAlign.center), const Divider(height:32), _Link(Icons.email, info.email, Uri(scheme:'mailto',path:info.email)), _Link(Icons.phone, info.phone, Uri(scheme:'tel',path:info.phone)), _Link(Icons.location_on, info.location, null), const SizedBox(height:18), ...List.generate(labels.length,(i)=>ListTile(selected:i==selected,selectedColor:AppColors.teal,leading:Icon(icons[i]),title:Text(labels[i]),onTap:()=>onTap(i))), const Spacer(), Text(info.availability, style:const TextStyle(color:AppColors.amber,fontWeight:FontWeight.bold))]));}
class LanguageSwitch extends StatelessWidget{ const LanguageSwitch({super.key, required this.language, required this.onChanged}); final SiteLanguage language; final ValueChanged<bool> onChanged; @override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:6), decoration:BoxDecoration(color:AppColors.background,border:Border.all(color:AppColors.border),borderRadius:BorderRadius.circular(999)), child:Row(mainAxisSize:MainAxisSize.min, children:[Text('EN', style:TextStyle(fontSize:12,fontWeight:FontWeight.w800,color:language==SiteLanguage.en?AppColors.teal:AppColors.muted)), Switch(value:language==SiteLanguage.es,onChanged:onChanged,activeColor:AppColors.teal,materialTapTargetSize:MaterialTapTargetSize.shrinkWrap), Text('ES', style:TextStyle(fontSize:12,fontWeight:FontWeight.w800,color:language==SiteLanguage.es?AppColors.teal:AppColors.muted))]));}
class _Link extends StatelessWidget{ const _Link(this.icon,this.text,this.uri); final IconData icon; final String text; final Uri? uri; @override Widget build(BuildContext context)=>InkWell(onTap:uri==null?null:()=>launchUrl(uri!), child:Padding(padding:const EdgeInsets.symmetric(vertical:6), child:Row(children:[Icon(icon,size:16,color:AppColors.teal), const SizedBox(width:8), Expanded(child:Text(text, style:const TextStyle(fontSize:12,color:AppColors.muted)))])));}
extension on int { Duration get ms=>Duration(milliseconds:this); }
