import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:http/http.dart' as http;
import '../data/cv_data.dart';
import '../theme/app_theme.dart';

class ChatMessage { ChatMessage(this.role, this.content); final String role; final String content; Map<String,String> toJson()=>{'role':role,'content':content}; }

class ChatbotWidget extends StatefulWidget { const ChatbotWidget({super.key}); @override State<ChatbotWidget> createState()=>_ChatbotWidgetState();}
class _ChatbotWidgetState extends State<ChatbotWidget>{
  final messages=<ChatMessage>[ChatMessage('assistant','¡Hola! Soy el asistente de Luis. Pregúntame sobre su experiencia, skills o disponibilidad.')];
  final input=TextEditingController(); final scroll=ScrollController(); bool open=false; bool typing=false;
  @override void dispose(){input.dispose();scroll.dispose();super.dispose();}
  void _bottom()=>WidgetsBinding.instance.addPostFrameCallback((_){ if(scroll.hasClients) scroll.animateTo(scroll.position.maxScrollExtent, duration:250.ms, curve:Curves.easeOut);});
  Future<void> _send() async { final text=input.text.trim(); if(text.isEmpty||typing)return; setState((){messages.add(ChatMessage('user',text)); input.clear(); typing=true;}); _bottom(); try{ final history=messages.length>21?messages.sublist(messages.length-21):messages; final res=await http.post(Uri.parse(chatbotUrl), headers:{'Content-Type':'application/json'}, body:jsonEncode({'message':text,'history':history.where((m)=>m.role!='system').map((m)=>m.toJson()).toList()})); final data=jsonDecode(res.body) as Map<String,dynamic>; setState(()=>messages.add(ChatMessage('assistant', data['reply']?.toString() ?? 'No recibí una respuesta válida.'))); } catch(_){ setState(()=>messages.add(ChatMessage('assistant','No pude conectar con el chatbot. Verifica la URL configurada en `cv_data.dart`.'))); } finally { setState(()=>typing=false); _bottom(); }}
  @override Widget build(BuildContext context){ final mobile=MediaQuery.sizeOf(context).width<700; return Positioned(right: mobile&&open?0:20, bottom: mobile&&open?0:20, child: open?_panel(mobile):FloatingActionButton(onPressed:()=>setState(()=>open=true), backgroundColor:AppColors.teal, foregroundColor:AppColors.background, child:const Icon(Icons.chat_bubble_outline)));}
  Widget _panel(bool mobile)=>Container(width:mobile?MediaQuery.sizeOf(context).width:300, height:mobile?MediaQuery.sizeOf(context).height:450, decoration:BoxDecoration(color:AppColors.background,border:Border.all(color:AppColors.teal.withValues(alpha:.5)),borderRadius:BorderRadius.circular(mobile?0:22),boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.35), blurRadius:24)]), child:Column(children:[Container(padding:const EdgeInsets.all(14), decoration:const BoxDecoration(color:AppColors.card), child:Row(children:[const CircleAvatar(backgroundColor:AppColors.teal, child:Text('LC', style:TextStyle(color:AppColors.background,fontWeight:FontWeight.bold))), const SizedBox(width:10), const Expanded(child:Text('Asistente de Luis', style:TextStyle(fontWeight:FontWeight.bold))), IconButton(onPressed:()=>setState(()=>open=false), icon:const Icon(Icons.close))])), Expanded(child:ListView(controller:scroll, padding:const EdgeInsets.all(12), children:[...messages.map(_bubble), if(typing) const _Typing()])), Padding(padding:const EdgeInsets.all(10), child:Row(children:[Expanded(child:TextField(controller:input, onSubmitted:(_)=>_send(), decoration:const InputDecoration(hintText:'Escribe tu pregunta...', border:OutlineInputBorder()))), const SizedBox(width:8), IconButton.filled(onPressed:_send, icon:const Icon(Icons.send))]))]));
  Widget _bubble(ChatMessage m){ final user=m.role=='user'; return Align(alignment:user?Alignment.centerRight:Alignment.centerLeft, child:Container(constraints:const BoxConstraints(maxWidth:245), margin:const EdgeInsets.symmetric(vertical:5), padding:const EdgeInsets.all(12), decoration:BoxDecoration(color:user?AppColors.teal:AppColors.card,borderRadius:BorderRadius.circular(16)), child:user?Text(m.content, style:const TextStyle(color:AppColors.background)):MarkdownBody(data:m.content, styleSheet:MarkdownStyleSheet(p:const TextStyle(color:AppColors.text)))));}
}
class _Typing extends StatelessWidget { const _Typing(); @override Widget build(BuildContext context)=>Align(alignment:Alignment.centerLeft, child:Container(padding:const EdgeInsets.all(12), decoration:BoxDecoration(color:AppColors.card,borderRadius:BorderRadius.circular(16)), child:Row(mainAxisSize:MainAxisSize.min, children:List.generate(3,(i)=>Container(width:6,height:6,margin:const EdgeInsets.all(2),decoration:const BoxDecoration(color:AppColors.teal,shape:BoxShape.circle)).animate(onPlay:(c)=>c.repeat()).fadeIn(delay:(120*i).ms).then().fadeOut()))));}
