import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:http/http.dart' as http;
import 'package:provider/provider.dart';
import '../data/cv_data.dart';
import '../providers/chat_provider.dart';
import '../theme/app_theme.dart';

const _welcomeMessage = '¡Hola! 👋 Soy el asistente virtual de Luis Carlos.\nPuedo contarte sobre su experiencia, proyectos, stack técnico\no cómo contactarlo. ¿En qué puedo ayudarte?';
const _suggestions = ['💼 ¿Cuál es su experiencia?', '🛠️ ¿Qué stack maneja?', '📁 ¿Qué proyectos ha hecho?', '📬 ¿Cómo lo contacto?'];

class ChatbotWidget extends StatefulWidget { const ChatbotWidget({super.key}); @override State<ChatbotWidget> createState()=>_ChatbotWidgetState();}
class _ChatbotWidgetState extends State<ChatbotWidget>{
  final input=TextEditingController(); final scroll=ScrollController();
  @override void dispose(){input.dispose();scroll.dispose();super.dispose();}
  void _bottom()=>WidgetsBinding.instance.addPostFrameCallback((_){ if(scroll.hasClients) scroll.animateTo(scroll.position.maxScrollExtent, duration:250.ms, curve:Curves.easeOut);});
  Future<void> _send([String? value]) async { final chat=context.read<ChatProvider>(); final text=(value ?? input.text).trim(); if(text.isEmpty||chat.typing)return; chat.addUserMessage(text); input.clear(); _bottom(); try{ final history=chat.messages.length>21?chat.messages.sublist(chat.messages.length-21):chat.messages; final res=await http.post(Uri.parse(chatbotUrl), headers:{'Content-Type':'application/json'}, body:jsonEncode({'message':text,'history':history.where((m)=>m.role!='system').map((m)=>m.toJson()).toList()})); if (res.statusCode == 429) { chat.addAssistantMessage('Estás enviando mensajes muy rápido. Espera unos segundos e intenta de nuevo. 😊'); return; } final data=jsonDecode(res.body) as Map<String,dynamic>; chat.addAssistantMessage(data['reply']?.toString() ?? 'No recibí una respuesta válida.'); } catch(_){ chat.addAssistantMessage('No pude conectar con el chatbot. Verifica la URL configurada en `cv_data.dart`.'); } finally { chat.setTyping(false); _bottom(); }}
  @override Widget build(BuildContext context){ final chat=context.watch<ChatProvider>(); final mobile=MediaQuery.sizeOf(context).width<700; return Positioned(right: mobile&&chat.open?0:20, bottom: mobile&&chat.open?0:20, child: chat.open?_panel(mobile, chat):_AiEntryButton(onTap:context.read<ChatProvider>().openChat, compact:mobile));}
  Widget _panel(bool mobile, ChatProvider chat)=>Container(width:mobile?MediaQuery.sizeOf(context).width:340, height:mobile?MediaQuery.sizeOf(context).height:500, decoration:BoxDecoration(color:AppColors.background,border:Border.all(color:AppColors.teal.withValues(alpha:.5)),borderRadius:BorderRadius.circular(mobile?0:22),boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.35), blurRadius:24)]), child:Column(children:[Container(padding:const EdgeInsets.all(14), decoration:const BoxDecoration(color:AppColors.card), child:Row(children:[const CircleAvatar(backgroundColor:AppColors.teal, child:Text('IA', style:TextStyle(color:AppColors.background,fontWeight:FontWeight.bold))), const SizedBox(width:10), const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Asistente IA de Luis', style:TextStyle(fontWeight:FontWeight.bold)), SizedBox(height:2), Text('Responde sobre experiencia, skills y disponibilidad', style:TextStyle(fontSize:11,color:AppColors.muted))])), IconButton(onPressed:context.read<ChatProvider>().closeChat, icon:const Icon(Icons.close))])), Expanded(child:ListView(controller:scroll, padding:const EdgeInsets.all(12), children:[if(chat.showWelcome) _bubble(ChatMessage('assistant',_welcomeMessage)).animate().fadeIn(duration:300.ms), if(chat.showWelcome&&chat.suggestionsVisible) _SuggestionChips(onSelected:_send), ...chat.messages.map(_bubble), if(chat.typing) const _Typing()])), Padding(padding:const EdgeInsets.all(10), child:Row(children:[Expanded(child:TextField(controller:input, onSubmitted:(_)=>_send(), decoration:const InputDecoration(hintText:'Ej: ¿Qué sabe de Flutter, R e IA?', border:OutlineInputBorder()))), const SizedBox(width:8), IconButton.filled(onPressed:_send, icon:const Icon(Icons.send))]))]));
  Widget _bubble(ChatMessage m){ final user=m.role=='user'; return Align(alignment:user?Alignment.centerRight:Alignment.centerLeft, child:Container(constraints:const BoxConstraints(maxWidth:275), margin:const EdgeInsets.symmetric(vertical:5), padding:const EdgeInsets.all(12), decoration:BoxDecoration(color:user?AppColors.teal:AppColors.card,borderRadius:BorderRadius.circular(16)), child:user?Text(m.content, style:const TextStyle(color:AppColors.background)):MarkdownBody(data:m.content, styleSheet:MarkdownStyleSheet(p:const TextStyle(color:AppColors.text)))));}
}
class _SuggestionChips extends StatelessWidget { const _SuggestionChips({required this.onSelected}); final ValueChanged<String> onSelected; @override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(top:4,bottom:10), child:Wrap(spacing:8, runSpacing:8, children:_suggestions.map((text)=>ActionChip(label:Text(text, style:const TextStyle(fontSize:12,color:AppColors.text)), backgroundColor:const Color(0xFF1F2937), side:const BorderSide(color:AppColors.teal), onPressed:()=>onSelected(text), materialTapTargetSize:MaterialTapTargetSize.shrinkWrap)).toList())); }
class _AiEntryButton extends StatelessWidget { const _AiEntryButton({required this.onTap, required this.compact}); final VoidCallback onTap; final bool compact; @override Widget build(BuildContext context)=>Stack(clipBehavior:Clip.none, children:[Material(color:Colors.transparent, child:InkWell(onTap:onTap, borderRadius:BorderRadius.circular(28), child:Container(padding:EdgeInsets.symmetric(horizontal:compact?16:20, vertical:14), decoration:BoxDecoration(gradient:const LinearGradient(colors:[AppColors.teal, Color(0xFF7C3AED)]), borderRadius:BorderRadius.circular(28), boxShadow:[BoxShadow(color:AppColors.teal.withValues(alpha:.42), blurRadius:28, spreadRadius:2)]), child:Row(mainAxisSize:MainAxisSize.min, children:[const Icon(Icons.auto_awesome, color:AppColors.background), if(!compact) ...[const SizedBox(width:10), const Text('Pregúntale a mi IA', style:TextStyle(color:AppColors.background,fontWeight:FontWeight.w900)), const SizedBox(width:8), const Icon(Icons.chat_bubble_outline, color:AppColors.background,size:18)]])))), Positioned(top:-12,right:compact?-6:8, child:Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:4), decoration:BoxDecoration(color:AppColors.amber,borderRadius:BorderRadius.circular(999)), child:const Text('Nuevo', style:TextStyle(color:AppColors.background,fontSize:11,fontWeight:FontWeight.w900))))]).animate(onPlay:(c)=>c.repeat()).scale(begin:const Offset(1.0,1.0), end:const Offset(1.08,1.08), duration:1200.ms, curve:Curves.easeInOut).then().scale(begin:const Offset(1.08,1.08), end:const Offset(1.0,1.0), duration:1200.ms, curve:Curves.easeInOut); }
class _Typing extends StatelessWidget { const _Typing(); @override Widget build(BuildContext context)=>Align(alignment:Alignment.centerLeft, child:Container(padding:const EdgeInsets.all(12), decoration:BoxDecoration(color:AppColors.card,borderRadius:BorderRadius.circular(16)), child:Row(mainAxisSize:MainAxisSize.min, children:List.generate(3,(i)=>Container(width:6,height:6,margin:const EdgeInsets.all(2),decoration:const BoxDecoration(color:AppColors.teal,shape:BoxShape.circle)).animate(onPlay:(c)=>c.repeat()).fadeIn(delay:(120*i).ms).then().fadeOut()))));}
extension on int { Duration get ms=>Duration(milliseconds:this); }
