import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:http/http.dart' as http;
import '../data/cv_data.dart';
import '../theme/app_theme.dart';

class ChatMessage { ChatMessage(this.role, this.content); final String role; final String content; Map<String,String> toJson()=>{'role':role,'content':content}; }

class ChatbotWidget extends StatefulWidget { const ChatbotWidget({super.key}); @override State<ChatbotWidget> createState()=>_ChatbotWidgetState();}
class _ChatbotWidgetState extends State<ChatbotWidget>{
  final messages=<ChatMessage>[ChatMessage('assistant','¡Hola! Soy el asistente de Luis. Pregúntame sobre su experiencia, skills o disponibilidad.')];
  final input=TextEditingController(); final scroll=ScrollController(); bool open=false; bool typing=false;
  @override void dispose(){input.dispose();scroll.dispose();super.dispose();}
  void _bottom()=>WidgetsBinding.instance.addPostFrameCallback((_){ if(scroll.hasClients) scroll.animateTo(scroll.position.maxScrollExtent, duration:250.ms, curve:Curves.easeOut);});
  Future<void> _send() async { final text=input.text.trim(); if(text.isEmpty||typing)return; setState((){messages.add(ChatMessage('user',text)); input.clear(); typing=true;}); _bottom(); try{ final history=messages.length>21?messages.sublist(messages.length-21):messages; final res=await http.post(Uri.parse(chatbotUrl), headers:{'Content-Type':'application/json'}, body:jsonEncode({'message':text,'history':history.where((m)=>m.role!='system').map((m)=>m.toJson()).toList()})); final data=jsonDecode(res.body) as Map<String,dynamic>; setState(()=>messages.add(ChatMessage('assistant', data['reply']?.toString() ?? 'No recibí una respuesta válida.'))); } catch(_){ setState(()=>messages.add(ChatMessage('assistant','No pude conectar con el chatbot. Verifica la URL configurada en `cv_data.dart`.'))); } finally { setState(()=>typing=false); _bottom(); }}
  @override Widget build(BuildContext context){ final mobile=MediaQuery.sizeOf(context).width<700; return Positioned(right: mobile&&open?0:20, bottom: mobile&&open?0:20, child: open?_panel(mobile):_AiEntryButton(onTap:()=>setState(()=>open=true), compact:mobile));}
  Widget _panel(bool mobile)=>Container(width:mobile?MediaQuery.sizeOf(context).width:340, height:mobile?MediaQuery.sizeOf(context).height:500, decoration:BoxDecoration(color:AppColors.background,border:Border.all(color:AppColors.teal.withValues(alpha:.5)),borderRadius:BorderRadius.circular(mobile?0:22),boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.35), blurRadius:24)]), child:Column(children:[Container(padding:const EdgeInsets.all(14), decoration:const BoxDecoration(color:AppColors.card), child:Row(children:[const CircleAvatar(backgroundColor:AppColors.teal, child:Text('IA', style:TextStyle(color:AppColors.background,fontWeight:FontWeight.bold))), const SizedBox(width:10), const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Asistente IA de Luis', style:TextStyle(fontWeight:FontWeight.bold)), SizedBox(height:2), Text('Responde sobre experiencia, skills y disponibilidad', style:TextStyle(fontSize:11,color:AppColors.muted))])), IconButton(onPressed:()=>setState(()=>open=false), icon:const Icon(Icons.close))])), Expanded(child:ListView(controller:scroll, padding:const EdgeInsets.all(12), children:[...messages.map(_bubble), if(typing) const _Typing()])), Padding(padding:const EdgeInsets.all(10), child:Row(children:[Expanded(child:TextField(controller:input, onSubmitted:(_)=>_send(), decoration:const InputDecoration(hintText:'Ej: ¿Qué sabe de Flutter, R e IA?', border:OutlineInputBorder()))), const SizedBox(width:8), IconButton.filled(onPressed:_send, icon:const Icon(Icons.send))]))]));
  Widget _bubble(ChatMessage m){ final user=m.role=='user'; return Align(alignment:user?Alignment.centerRight:Alignment.centerLeft, child:Container(constraints:const BoxConstraints(maxWidth:275), margin:const EdgeInsets.symmetric(vertical:5), padding:const EdgeInsets.all(12), decoration:BoxDecoration(color:user?AppColors.teal:AppColors.card,borderRadius:BorderRadius.circular(16)), child:user?Text(m.content, style:const TextStyle(color:AppColors.background)):MarkdownBody(data:m.content, styleSheet:MarkdownStyleSheet(p:const TextStyle(color:AppColors.text)))));}
}
class _AiEntryButton extends StatelessWidget { const _AiEntryButton({required this.onTap, required this.compact}); final VoidCallback onTap; final bool compact; @override Widget build(BuildContext context)=>Stack(clipBehavior:Clip.none, children:[Material(color:Colors.transparent, child:InkWell(onTap:onTap, borderRadius:BorderRadius.circular(28), child:Container(padding:EdgeInsets.symmetric(horizontal:compact?16:20, vertical:14), decoration:BoxDecoration(gradient:const LinearGradient(colors:[AppColors.teal, Color(0xFF7C3AED)]), borderRadius:BorderRadius.circular(28), boxShadow:[BoxShadow(color:AppColors.teal.withValues(alpha:.42), blurRadius:28, spreadRadius:2)]), child:Row(mainAxisSize:MainAxisSize.min, children:[const Icon(Icons.auto_awesome, color:AppColors.background), if(!compact) ...[const SizedBox(width:10), const Text('Pregúntale a mi IA', style:TextStyle(color:AppColors.background,fontWeight:FontWeight.w900)), const SizedBox(width:8), const Icon(Icons.chat_bubble_outline, color:AppColors.background,size:18)]])))), Positioned(top:-12,right:compact?-6:8, child:Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:4), decoration:BoxDecoration(color:AppColors.amber,borderRadius:BorderRadius.circular(999)), child:const Text('Nuevo', style:TextStyle(color:AppColors.background,fontSize:11,fontWeight:FontWeight.w900))))]).animate(onPlay:(c)=>c.repeat(reverse:true)).scale(begin:const Offset(1,1), end:const Offset(1.04,1.04), duration:900.ms); }
class _Typing extends StatelessWidget { const _Typing(); @override Widget build(BuildContext context)=>Align(alignment:Alignment.centerLeft, child:Container(padding:const EdgeInsets.all(12), decoration:BoxDecoration(color:AppColors.card,borderRadius:BorderRadius.circular(16)), child:Row(mainAxisSize:MainAxisSize.min, children:List.generate(3,(i)=>Container(width:6,height:6,margin:const EdgeInsets.all(2),decoration:const BoxDecoration(color:AppColors.teal,shape:BoxShape.circle)).animate(onPlay:(c)=>c.repeat()).fadeIn(delay:(120*i).ms).then().fadeOut()))));}
extension on int { Duration get ms=>Duration(milliseconds:this); }
